## Word Embedding Techniques using Embedding Layer in Keras

In [9]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable


In [15]:
import sys
!{sys.executable} -m pip install tensorflow

  Using cached absl_py-2.3.0-py3-none-any.whl.metadata (2.4 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached requests-2.32.4-py3-none-any.whl.metadata (4.9 kB)
  Using cached termcolor-3.1.0-py3-none-any.whl.metadata (6.4 kB)
  Using cached tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
  Using cached keras-3.10.0-py3-none-any.whl.metadata (6.0 kB)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
  Using cached werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
  Using cached rich-14.0.0-py3-none-any.whl.

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


   ---------- --------------------------- 101.7/375.7 MB 543.8 kB/s eta 0:08:24
   ---------- --------------------------- 101.7/375.7 MB 543.8 kB/s eta 0:08:24
   ---------- --------------------------- 102.0/375.7 MB 546.4 kB/s eta 0:08:22
   ---------- --------------------------- 102.0/375.7 MB 546.4 kB/s eta 0:08:22
   ---------- --------------------------- 102.2/375.7 MB 545.5 kB/s eta 0:08:22
   ---------- --------------------------- 102.2/375.7 MB 545.5 kB/s eta 0:08:22
   ---------- --------------------------- 102.5/375.7 MB 558.9 kB/s eta 0:08:09
   ---------- --------------------------- 102.8/375.7 MB 562.5 kB/s eta 0:08:06
   ---------- --------------------------- 103.0/375.7 MB 566.9 kB/s eta 0:08:02
   ---------- --------------------------- 103.3/375.7 MB 570.7 kB/s eta 0:07:58
   ---------- --------------------------- 103.3/375.7 MB 570.7 kB/s eta 0:07:58
   ---------- --------------------------- 103.5/375.7 MB 585.0 kB/s eta 0:07:46
   ---------- --------------------------

In [17]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
# sentences (every sentence has diff length)
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [23]:
# Vocabulary size (large vocabulary size, good amt of feature representation) 
voc_size=500

#### One Hot Representation 

In [34]:
onehot_repr = [one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

#O/P - index no. where it is one 

[[428, 267, 404, 210], [428, 267, 404, 373], [428, 54, 404, 493], [260, 445, 291, 291, 195], [260, 445, 291, 291, 305], [222, 428, 64, 404, 450], [61, 378, 54, 291]]


#### Word Embedding Represntation

In [30]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [32]:
import numpy as np

In [56]:
# Pre padding   (Ensures that every sentence will have length=8 (either add 0 at beginning or last))
sent_length = 8    #maximum sentence legth = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)  #pre = 0 in forward
print(embedded_docs)

[[  0   0   0   0 428 267 404 210]
 [  0   0   0   0 428 267 404 373]
 [  0   0   0   0 428  54 404 493]
 [  0   0   0 260 445 291 291 195]
 [  0   0   0 260 445 291 291 305]
 [  0   0   0 222 428  64 404 450]
 [  0   0   0   0  61 378  54 291]]


In [38]:
#now input size is fixed

In [40]:
# Post padding (0 in last)
embedded_docs = pad_sequences(onehot_repr, padding = 'post', maxlen = sent_length)  #pre = 0 in forward
print(embedded_docs)

[[428 267 404 210   0   0   0   0]
 [428 267 404 373   0   0   0   0]
 [428  54 404 493   0   0   0   0]
 [260 445 291 291 195   0   0   0]
 [260 445 291 291 305   0   0   0]
 [222 428  64 404 450   0   0   0]
 [ 61 378  54 291   0   0   0   0]]


In [58]:
dim = 10    #(for each feature, 10 dimensions[]

In [60]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))   #Embedding layer will work similar to Word2Vec
# 10 = no. of features for each vector
model.compile('adam', 'mse') 

In [62]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [64]:
# 'the glass of milk'
embedded_docs[0]

array([  0,   0,   0,   0, 428, 267, 404, 210])

In [66]:
model.predict(embedded_docs[0])    #1st sentence

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step


array([[-0.02007862, -0.02584435, -0.01724929,  0.02191228, -0.04122832,
         0.04153753,  0.00793408, -0.01353461, -0.023348  ,  0.01910624],
       [-0.02007862, -0.02584435, -0.01724929,  0.02191228, -0.04122832,
         0.04153753,  0.00793408, -0.01353461, -0.023348  ,  0.01910624],
       [-0.02007862, -0.02584435, -0.01724929,  0.02191228, -0.04122832,
         0.04153753,  0.00793408, -0.01353461, -0.023348  ,  0.01910624],
       [-0.02007862, -0.02584435, -0.01724929,  0.02191228, -0.04122832,
         0.04153753,  0.00793408, -0.01353461, -0.023348  ,  0.01910624],
       [ 0.02613517,  0.01840321, -0.02283095,  0.01656907,  0.04892751,
        -0.01397438, -0.00672959,  0.01631344,  0.00804422,  0.0076733 ],
       [ 0.03715623, -0.03400601, -0.01337973,  0.003267  ,  0.03913369,
        -0.03503673,  0.00042027,  0.01026278, -0.04439042, -0.00090066],
       [-0.03816791, -0.00026406,  0.00411147,  0.03227982,  0.00795102,
         0.00130365,  0.01435002,  0.04211149

In [68]:
# every vector is represented by 10 dimensions each.

In [76]:
print(model.predict(embedded_docs[1]))     #2nd sentence

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
[[-0.02007862 -0.02584435 -0.01724929  0.02191228 -0.04122832  0.04153753
   0.00793408 -0.01353461 -0.023348    0.01910624]
 [-0.02007862 -0.02584435 -0.01724929  0.02191228 -0.04122832  0.04153753
   0.00793408 -0.01353461 -0.023348    0.01910624]
 [-0.02007862 -0.02584435 -0.01724929  0.02191228 -0.04122832  0.04153753
   0.00793408 -0.01353461 -0.023348    0.01910624]
 [-0.02007862 -0.02584435 -0.01724929  0.02191228 -0.04122832  0.04153753
   0.00793408 -0.01353461 -0.023348    0.01910624]
 [ 0.02613517  0.01840321 -0.02283095  0.01656907  0.04892751 -0.01397438
  -0.00672959  0.01631344  0.00804422  0.0076733 ]
 [ 0.03715623 -0.03400601 -0.01337973  0.003267    0.03913369 -0.03503673
   0.00042027  0.01026278 -0.04439042 -0.00090066]
 [-0.03816791 -0.00026406  0.00411147  0.03227982  0.00795102  0.00130365
   0.01435002  0.04211149  0.03780066 -0.0189147 ]
 [ 0.00648201 -0.00798405 -0.0251147   0.04350232 -0.00296343 -0.02836239
   0.01731011